FROM golang:alpine AS build

WORKDIR /app
COPY *go*  /app/

RUN go build

FROM alpine

WORKDIR /app
COPY --from=build /app/search-go /app/
COPY templates /app/templates

CMD ["/app/search-go"]
EXPOSE 9000
